env: walker2d-random-v2
policy: SCQ
eval_episodes: 10
eval_freq: 5000
# TD3
discount: 0.99
actor_learning_rate: 0.0003
critic_learning_rate: 0.0003
actor_num_hidden_layers: 2
critic_num_hidden_layers: 2
normalize_reward: False
use_layernormalization: False
use_actor_scheduler: False
log_sig_min: -3.0

actor_clip_grad_norm: 1.0
critic_clip_grad_norm: 1.0

# Trust Region CQL
critic_penalty_coef: 15.0
