env: antmaze-medium-play-v2
policy: SAC
eval_episodes: 100
eval_freq: 50000

# Experiment
discount: 0.99
actor_learning_rate: 0.0001
critic_learning_rate: 0.0003
actor_num_hidden_layers: 2
critic_num_hidden_layers: 2
normalize_reward: True
use_layernormalization: False

# Trust Region CQL
actor_penalty_coef: 1.0

option_name: "SAC"
