env: antmaze-medium-play-v2
policy: SCQ
eval_episodes: 100
eval_freq: 50000

discount: 0.99
actor_learning_rate: 0.0001
critic_learning_rate: 0.0003
actor_num_hidden_layers: 2
critic_num_hidden_layers: 2
normalize_reward: True
use_layernormalization: False

actor_penalty_coef: 1.0
critic_penalty_coef: 0.1

data_size_ratio: 0.3

option_name: "ratio_30"
