env: antmaze-medium-play-v2
policy: SCQ
eval_episodes: 100
eval_freq: 5000
# TD3
discount: 0.99
actor_learning_rate: 0.0001
critic_learning_rate: 0.0003
actor_num_hidden_layers: 2
critic_num_hidden_layers: 2
normalize_reward: True
use_layernormalization: False
# TD3 + BC
actor_penalty_coef: 1.0
critic_penalty_coef: 0.1
