env: antmaze-umaze-diverse-v2
policy: SCQ
eval_episodes: 100
eval_freq: 50000
# TD3
discount: 0.99
actor_learning_rate: 0.0001
critic_learning_rate: 0.0003
actor_num_hidden_layers: 2
critic_num_hidden_layers: 2
normalize_reward: True
use_layernormalization: False
log_sig_min: -3.0
use_actor_scheduler: True

actor_clip_grad_norm: 1.0
critic_clip_grad_norm: 1.0

actor_penalty_coef: 1.0
critic_penalty_coef: 0.3
